#!/bin/bash
# Copyright 2014 Francisco Medina Lopez <paco.medina@comunidad.unam.mx>

# Lee el archivo de configuracion
. ../config

# Detiene el servicio NetworkManager 
echo "[+] Deteniendo el servicio NetworkManager..."
pkill NetworkManager
pkill dhclient

# Configura los parametros de la red externa
echo "[+] Configurando los parametros de la red externa..."
ifconfig eth0 down
ifconfig eth0 $IP netmask $MASK up
route add default gw $GW
echo "nameserver $DNS">/etc/resolv.conf


# Configura los parametros de la red interna
echo "[+] Configurando los parametros de la red interna..."
ifconfig eth0:1 down
ifconfig eth0:1 $IP_INT netmask $MASK_INT up

