#!/bin/bash
# Copyright 2014 Francisco Medina Lopez <paco.medina@comunidad.unam.mx>

# Lee el archivo de configuracion
. ../config

echo "[+] Configurando los parámetros de red del CLIENTE..."

# Configura los parametros de la red interna para servidor red interna
ifconfig eth0 down
ifconfig eth0 $IP_CLI_INT netmask $MASK_INT up
route add default gw $IP_INT
echo "nameserver $DNS">/etc/resolv.conf

